#!/bin/sh
# misc
alias df='df -h'
alias whereis='find . -iname'
alias grep='egrep'
alias tcpy='pwd | urxvtc'
alias poogle='ping www.google.com'
alias clr='clear'

# restart
alias rebash='source ~/.bashrc'
alias remonad='xmonad --recompile && xmonad --restart'
alias remacs='emacsclient -e "(kill-emacs)"; emacs --daemon'

# ls
alias ls='ls --color=auto -p'
alias ll='ls -l'
alias lf='ls -f'
alias la='ls -a'
alias lal='ls -al'

# why?
alias al='sl -a'
alias lll='sl -l'

# typos
alias :e='vim'
alias :r='!!'

# rlwrap
alias ocaml='rlwrap ocaml'

alias octave=octave-cli

# emacs client in terminal
alias em="emacsclient -t"

alias R="R --no-save"

alias op="exo-open"

toup(){
    touch $1 && op $1
}

steam(){
    LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' /bin/steam
}

alias todo="op ~/TODO/todo"
