#!/bin/sh
export EDITOR="emacsclient -c"
export PAGER=vimpager
export PATH=$PATH:/home/m/conf/bin:/home/m/.cabal/bin:/usr/lib/smlnj/bin
export SMLNJ_HOME=/usr/lib/smlnj/
export PYTHONPATH=$PYTHONPATH:/home/m/git-stuff/gudhi/build/cython

# JULIA
export CONDA_JL_VERSION=2
export JULIA_NUM_THREADS=4

# source /usr/bin/thisroot.sh
