#!/bin/bash
# run at startup

# input & stuff
#setxkbmap si
setxkbmap us
setxkbmap -option compose:ralt
syndaemon -t -k -i 1 -d &     # disable touchpad when typing
xset -b                       # disable beep
setxkbmap -option ctrl:nocaps # disable caps
xmodmap ~/conf/dotfiles/.xmodmap

# daemons
urxvtd &
redshift -l -36.8:174.8 -t 6000:3500 &

# start emacs daemon
emacs --daemon &

# xmonad + restore panels
xmonad --replace &
sleep 1
xfce4-panel --restart
