#!/bin/bash
# run at startup

# input & stuff
setxkbmap si                  # set keyboard to slovene
syndaemon -t -k -i 1 -d &     # disable touchpad when typing
xset -b                       # disable beep
setxkbmap -option ctrl:nocaps # disable caps
xmodmap ~/conf/dotfiles/.xmodmap

# daemons
urxvtd &
redshift -l 46:14 -t 6000:3500 &

# start emacs daemon
emacs --daemon &

# xmonad + restore panels
xmonad --replace &
sleep 4 && kill -9 $(pgrep xfce4-panel) && sleep 2 && xfce4-panel &
